# Server configurations
server:
  port: :6060
  basepath: /pea

# Application specific configurations
application:
  name: policy-enf-agent

spire:
  enable: true
  #agent: agents-operator.accuknox-agent.svc.cluster.local:9091
  agent: "unix:///var/run/spire/agent.sock"

#this endpoint is to call fetch policy API
endpoint:
  urlendpoint: /pps/api/v1/policy-provider/fetch-policy
    #baseurlendpoint: https://localhost:2882
  baseurlendpoint: https://pps.stage.accuknox.com
    #urllocal: /pps/api/v1/policy-provider/fetch-policy
    #baselocal: https://localhost:2882

#this endpoint is to call change status API
statusendpoint:
  #endpoint: https://localhost:2882/pps/api/v1/policy-provider/change-status-policy
  endpoint: https://pps.stage.accuknox.com/pps/api/v1/policy-provider/change-status-policy

#sync time for gocron
syncuptime:
  t: 5

#annotations endpoint
annotation:
  statusendpoint: /pps/api/v1/policy-provider/update-annotation-status
  annotationendpoint: /pps/api/v1/policy-provider/fetch-annotations
    #basepath: https://localhost:2882
  basepath: https://pps.stage.accuknox.com

non-k8s:
  enable: true
  policy-server-port: 32770
